security:
  user:
    name: buzz
    password: infinity

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

#logging:
#  level:
#    org.springframework.data.rest: debug

spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: tacocloud

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://127.0.0.1/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN
