# TODO: add security section

taco:
  orders:
    pageSize: 10

discount:
  codes:
    abcdef: 10

spring:
  data:
    rest:
      base-path: /api
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: user
    password: pass

---

spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

  logging:
    level:
      tacos: WARN
